# Generated by Django 5.1.4 on 2025-01-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_expense_amount_alter_profile_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expenses',
            field=models.FloatField(default=0, null=True),
        ),
    ]
